In [1]:
# import libraries
import numpy as np
import pandas as pd
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import LabelEncoder, MinMaxScaler

In [2]:
raw_train= pd.read_csv('dataset/train.csv')
raw_test= pd.read_csv('dataset/test.csv')

In [3]:
raw_train.head()

Loan_ID Gender Married Dependents     Education Self_Employed  \
0  LP001002   Male      No          0      Graduate            No   
1  LP001003   Male     Yes          1      Graduate            No   
2  LP001005   Male     Yes          0      Graduate           Yes   
3  LP001006   Male     Yes          0  Not Graduate            No   
4  LP001008   Male      No          0      Graduate            No   

   ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0             5849                0.0         NaN             360.0   
1             4583             1508.0       128.0             360.0   
2             3000                0.0        66.0             360.0   
3             2583             2358.0       120.0             360.0   
4             6000                0.0       141.0             360.0   

   Credit_History Property_Area Loan_Status  
0             1.0         Urban           Y  
1             1.0         Rural           N  
2             1.0         Urban           Y  
3             1.0         Urban           Y  
4             1.0         Urban           Y

In [4]:
raw_train.nunique()

Loan_ID              614
Gender                 2
Married                2
Dependents             4
Education              2
Self_Employed          2
ApplicantIncome      505
CoapplicantIncome    287
LoanAmount           203
Loan_Amount_Term      10
Credit_History         2
Property_Area          3
Loan_Status            2
dtype: int64

In [5]:
raw_train.shape

(614, 13)

In [6]:
train_df = raw_train.copy()
test_df = raw_test.copy()

In [7]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Loan_ID            614 non-null    object 
 1   Gender             601 non-null    object 
 2   Married            611 non-null    object 
 3   Dependents         599 non-null    object 
 4   Education          614 non-null    object 
 5   Self_Employed      582 non-null    object 
 6   ApplicantIncome    614 non-null    int64  
 7   CoapplicantIncome  614 non-null    float64
 8   LoanAmount         592 non-null    float64
 9   Loan_Amount_Term   600 non-null    float64
 10  Credit_History     564 non-null    float64
 11  Property_Area      614 non-null    object 
 12  Loan_Status        614 non-null    object 
dtypes: float64(4), int64(1), object(8)
memory usage: 62.5+ KB


In [8]:
test_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 362 entries, 0 to 361
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Loan_ID            362 non-null    object 
 1   Gender             351 non-null    object 
 2   Married            362 non-null    object 
 3   Dependents         353 non-null    object 
 4   Education          362 non-null    object 
 5   Self_Employed      339 non-null    object 
 6   ApplicantIncome    362 non-null    int64  
 7   CoapplicantIncome  362 non-null    int64  
 8   LoanAmount         362 non-null    int64  
 9   Loan_Amount_Term   356 non-null    float64
 10  Credit_History     333 non-null    float64
 11  Property_Area      362 non-null    object 
dtypes: float64(2), int64(3), object(7)
memory usage: 34.1+ KB


In [9]:
train_y = train_df['Loan_Status'].copy()

In [10]:
 train_df.drop(columns=['Loan_Status'],inplace= True)

In [11]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Loan_ID            614 non-null    object 
 1   Gender             601 non-null    object 
 2   Married            611 non-null    object 
 3   Dependents         599 non-null    object 
 4   Education          614 non-null    object 
 5   Self_Employed      582 non-null    object 
 6   ApplicantIncome    614 non-null    int64  
 7   CoapplicantIncome  614 non-null    float64
 8   LoanAmount         592 non-null    float64
 9   Loan_Amount_Term   600 non-null    float64
 10  Credit_History     564 non-null    float64
 11  Property_Area      614 non-null    object 
dtypes: float64(4), int64(1), object(7)
memory usage: 57.7+ KB


In [12]:
# Dropping unncessary columns

train_df.drop(columns= 'Loan_ID', inplace=True)
test_df.drop(columns= 'Loan_ID', inplace=True)

In [13]:
train_df.columns

Index(['Gender', 'Married', 'Dependents', 'Education', 'Self_Employed',
       'ApplicantIncome', 'CoapplicantIncome', 'LoanAmount',
       'Loan_Amount_Term', 'Credit_History', 'Property_Area'],
      dtype='object')

In [14]:
#Duplicates

train_df[train_df.duplicated()]

Empty DataFrame
Columns: [Gender, Married, Dependents, Education, Self_Employed, ApplicantIncome, CoapplicantIncome, LoanAmount, Loan_Amount_Term, Credit_History, Property_Area]
Index: []

In [15]:
test_df[test_df.duplicated()]

Gender Married Dependents Education Self_Employed  ApplicantIncome  \
192   Male      No          0  Graduate           Yes             5833   

     CoapplicantIncome  LoanAmount  Loan_Amount_Term  Credit_History  \
192                  0         116             360.0             1.0   

    Property_Area  
192         Urban

In [16]:
test_df.drop_duplicates(inplace= True)

In [17]:
test_df[test_df.duplicated()]

Empty DataFrame
Columns: [Gender, Married, Dependents, Education, Self_Employed, ApplicantIncome, CoapplicantIncome, LoanAmount, Loan_Amount_Term, Credit_History, Property_Area]
Index: []

In [18]:
#missing values analysis

train_df.isna().sum()

Gender               13
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
dtype: int64

In [19]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Gender             601 non-null    object 
 1   Married            611 non-null    object 
 2   Dependents         599 non-null    object 
 3   Education          614 non-null    object 
 4   Self_Employed      582 non-null    object 
 5   ApplicantIncome    614 non-null    int64  
 6   CoapplicantIncome  614 non-null    float64
 7   LoanAmount         592 non-null    float64
 8   Loan_Amount_Term   600 non-null    float64
 9   Credit_History     564 non-null    float64
 10  Property_Area      614 non-null    object 
dtypes: float64(4), int64(1), object(6)
memory usage: 52.9+ KB


In [20]:
train_df.nunique()

Gender                 2
Married                2
Dependents             4
Education              2
Self_Employed          2
ApplicantIncome      505
CoapplicantIncome    287
LoanAmount           203
Loan_Amount_Term      10
Credit_History         2
Property_Area          3
dtype: int64

In [21]:
train_df.columns

Index(['Gender', 'Married', 'Dependents', 'Education', 'Self_Employed',
       'ApplicantIncome', 'CoapplicantIncome', 'LoanAmount',
       'Loan_Amount_Term', 'Credit_History', 'Property_Area'],
      dtype='object')

In [22]:
# Numrice --> mean
# Categorical --> mode
num_cols = ['ApplicantIncome', 'CoapplicantIncome', 'LoanAmount',
            'Loan_Amount_Term']

cat_cols = ['Gender', 'Married', 'Dependents', 'Education', 'Self_Employed',
             'Property_Area','Credit_History' ] 

In [23]:
cat_imputer = SimpleImputer(strategy= "most_frequent")
cat_imputer.fit(train_df[cat_cols])

train_df[cat_cols] = cat_imputer.transform(train_df[cat_cols])

test_df[cat_cols] = cat_imputer.transform(test_df[cat_cols])

In [24]:
num_imputer = SimpleImputer(strategy= "most_frequent")
num_imputer.fit(train_df[num_cols])

train_df[num_cols] = num_imputer.transform(train_df[num_cols])

test_df[num_cols] = num_imputer.transform(test_df[num_cols])

In [25]:
train_df.isna().sum()

Gender               0
Married              0
Dependents           0
Education            0
Self_Employed        0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
Property_Area        0
dtype: int64

In [26]:
train_df.head()

Gender Married Dependents     Education Self_Employed  ApplicantIncome  \
0   Male      No          0      Graduate            No           5849.0   
1   Male     Yes          1      Graduate            No           4583.0   
2   Male     Yes          0      Graduate           Yes           3000.0   
3   Male     Yes          0  Not Graduate            No           2583.0   
4   Male      No          0      Graduate            No           6000.0   

   CoapplicantIncome  LoanAmount  Loan_Amount_Term Credit_History  \
0                0.0       120.0             360.0            1.0   
1             1508.0       128.0             360.0            1.0   
2                0.0        66.0             360.0            1.0   
3             2358.0       120.0             360.0            1.0   
4                0.0       141.0             360.0            1.0   

  Property_Area  
0         Urban  
1         Rural  
2         Urban  
3         Urban  
4         Urban

In [27]:
# preprocessing as per the domain knowledge
train_df['ApplicantIncome'] = train_df['ApplicantIncome'] + train_df['CoapplicantIncome']
test_df['ApplicantIncome'] = test_df['ApplicantIncome'] + test_df['CoapplicantIncome']

#drop the coapplicant cols
train_df.drop(columns='CoapplicantIncome' , inplace = True )
test_df.drop(columns='CoapplicantIncome' , inplace = True )

In [28]:
train_df.head()

Gender Married Dependents     Education Self_Employed  ApplicantIncome  \
0   Male      No          0      Graduate            No           5849.0   
1   Male     Yes          1      Graduate            No           6091.0   
2   Male     Yes          0      Graduate           Yes           3000.0   
3   Male     Yes          0  Not Graduate            No           4941.0   
4   Male      No          0      Graduate            No           6000.0   

   LoanAmount  Loan_Amount_Term Credit_History Property_Area  
0       120.0             360.0            1.0         Urban  
1       128.0             360.0            1.0         Rural  
2        66.0             360.0            1.0         Urban  
3       120.0             360.0            1.0         Urban  
4       141.0             360.0            1.0         Urban

In [29]:
# application for LabelEncoder

train_df.nunique()

Gender                2
Married               2
Dependents            4
Education             2
Self_Employed         2
ApplicantIncome     554
LoanAmount          203
Loan_Amount_Term     10
Credit_History        2
Property_Area         3
dtype: int64

In [30]:
train_df.Dependents.unique()

array(['0', '1', '2', '3+'], dtype=object)

In [31]:
train_df.Property_Area.unique()

array(['Urban', 'Rural', 'Semiurban'], dtype=object)

In [32]:
for col in cat_cols:
    le= LabelEncoder()
    train_df[col]=le.fit_transform(train_df[col])
    test_df[col]=le.fit_transform(test_df[col])

In [33]:
train_df.head()

Gender  Married  Dependents  Education  Self_Employed  ApplicantIncome  \
0       1        0           0          0              0           5849.0   
1       1        1           1          0              0           6091.0   
2       1        1           0          0              1           3000.0   
3       1        1           0          1              0           4941.0   
4       1        0           0          0              0           6000.0   

   LoanAmount  Loan_Amount_Term  Credit_History  Property_Area  
0       120.0             360.0               1              2  
1       128.0             360.0               1              0  
2        66.0             360.0               1              2  
3       120.0             360.0               1              2  
4       141.0             360.0               1              2

In [34]:
num_cols.remove('CoapplicantIncome')

In [35]:
train_df[num_cols] = np.log(train_df[num_cols])
test_df[num_cols] = np.log(test_df[num_cols])

In [36]:
train_df.head()

Gender  Married  Dependents  Education  Self_Employed  ApplicantIncome  \
0       1        0           0          0              0         8.674026   
1       1        1           1          0              0         8.714568   
2       1        1           0          0              1         8.006368   
3       1        1           0          1              0         8.505323   
4       1        0           0          0              0         8.699515   

   LoanAmount  Loan_Amount_Term  Credit_History  Property_Area  
0    4.787492          5.886104               1              2  
1    4.852030          5.886104               1              0  
2    4.189655          5.886104               1              2  
3    4.787492          5.886104               1              2  
4    4.948760          5.886104               1              2

In [37]:
#scaling

minmax= MinMaxScaler()

train_df = minmax.fit_transform(train_df)
test_df = minmax.transform(test_df)

In [40]:
train_df[:1]

array([[1.        , 0.        , 0.        , 0.        , 0.        ,
        0.34759045, 0.59493638, 0.9220137 , 1.        , 1.        ]])

In [41]:
# Model Building

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(train_df, train_y, test_size=0.3, random_state=0) 

In [42]:
X_train.shape ,y_train.shape , X_test.shape ,y_test.shape

((429, 10), (429,), (185, 10), (185,))

In [43]:
from sklearn.linear_model import LogisticRegression

log = LogisticRegression()
log.fit(X_train, y_train)

LogisticRegression()

In [44]:
y_pred_test = log.predict(X_test)

In [47]:
from sklearn.metrics import accuracy_score
acc = accuracy_score(y_test, y_pred_test)
print(f"accuracy is = {acc}")

accuracy is = 0.827027027027027


In [48]:
import joblib

joblib.dump(log , 'my_trained_model.pkl')

['my_trained_model.pkl']

In [49]:
final_model = joblib.load("my_trained_model.pkl")

In [50]:
final_model

LogisticRegression()

In [51]:
final_model.coef_ 

array([[ 0.02260368,  0.35244463,  0.39218756, -0.44041645, -0.04990522,
         0.013641  , -0.72407572,  0.23959891,  3.18118621,  0.22620238]])

In [52]:
log.coef_

array([[ 0.02260368,  0.35244463,  0.39218756, -0.44041645, -0.04990522,
         0.013641  , -0.72407572,  0.23959891,  3.18118621,  0.22620238]])